import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — Absovex",
  description:
    "Read the Absovex disclaimer regarding educational use, medical advice, and liability.",
};

const paragraphs = [
  "Absovex is an educational and informational tool designed to help users identify potential medication, supplement, food, beverage, and timing considerations based on the information submitted.",
  "Absovex does not provide medical advice, diagnosis, treatment, or medical care of any kind. The information generated by Absovex is not intended to replace consultation with a licensed physician, pharmacist, or other qualified healthcare professional.",
  "Users should always consult a qualified healthcare provider before starting, stopping, combining, spacing, or adjusting any medication, supplement, vitamin, mineral, or health-related routine.",
  "While Absovex aims to provide helpful educational guidance, we do not guarantee the accuracy, completeness, reliability, effectiveness, or suitability of any recommendation, report, schedule, timing suggestion, interaction summary, or informational output generated through the platform.",
  "Absovex does not establish a physician-patient, pharmacist-patient, or healthcare provider relationship with any user.",
  "The platform should not be used for emergency medical situations or urgent healthcare decisions. If you believe you are experiencing a medical emergency, contact emergency services or a licensed healthcare provider immediately.",
  "By using Absovex, you acknowledge and agree that you are solely responsible for how you interpret and use the information provided through the platform.",
];

export default function DisclaimerPage() {
  return (
    <div className="container py-16 lg:py-24 max-w-content-sm">
      <div className="max-w-3/4 mx-auto">
        <h1 className="mb-3 text-accent">Disclaimer</h1>
        <p className="text-sm text-muted mb-10">Effective Date: June 2026</p>
        <div className="flex flex-col gap-6">
          {paragraphs.map((text, i) => (
            <p key={i} className="text-base leading-8 text-muted">
              {text}
            </p>
          ))}
        </div>
      </div>
    </div>
  );
}
